import os
from dotenv import load_dotenv
load_dotenv()

MODE = os.getenv("MODE", "paper")
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")
DEEPSEEK_MODEL = "deepseek-chat"
SYMBOLS = ["SOL/USDT", "BTC/USDT", "ETH/USDT"]
PRIMARY_TIMEFRAME = "M5"
SECONDARY_TIMEFRAMES = ["M1", "M15"]
INITIAL_BALANCE = 10000.0
MAX_POSITIONS = 5
RISK_PER_TRADE = 0.005
MAX_DAILY_DRAWDOWN = 0.02
MAX_TOTAL_DRAWDOWN = 0.15
MIN_CONFIDENCE = 70
MIN_RISK_REWARD = 1.5
LATENCY_MS = 200
SLIPPAGE_FACTOR = 0.5
COMMISSION_RATE = 0.001
SIGNAL_GATE_ATR_THRESHOLD_PCT = 0.15
SIGNAL_GATE_MIN_SCORE = 2
MAX_DAILY_TOKEN_BUDGET = 0.10
CRYPTOPANIC_API_KEY = os.getenv("CRYPTOPANIC_API_KEY", "")
WHALE_ALERT_API_KEY = os.getenv("WHALE_ALERT_API_KEY", "")
WHALE_MIN_VALUE = 500000
FRED_API_KEY = os.getenv("FRED_API_KEY", "")
FRED_SERIES = "FEDFUNDS"
MT5_LOGIN = int(os.getenv("MT5_LOGIN", 0))
MT5_PASSWORD = os.getenv("MT5_PASSWORD", "")
MT5_SERVER = os.getenv("MT5_SERVER", "")
EXCHANGE_ID = os.getenv("EXCHANGE_ID", "binance")
EXCHANGE_API_KEY = os.getenv("EXCHANGE_API_KEY", "")
EXCHANGE_SECRET = os.getenv("EXCHANGE_SECRET", "")
DATABASE_PATH = "agent_memory.db"
SCAN_INTERVAL_SECONDS = 1
REFLECTION_HOUR = 0
